server:
  port: 8400

spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.14.75.238:3306/ejyy?useSSL=false&characterEncoding=UTF8
    username: root
    password: cyq0902
  redis:
    host: 1.14.64.16
    port: 6379
    database: 0
    timeout: 18000000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 1.14.75.238:8848
  rabbitmq:
    password: guest
    username: guest
    host: 1.14.75.238
    port: 5672
    virtual-host: /

mybatis-plus:
  type-aliases-package: com.openlab.notice.mapper
  global-config:
    db-config:
      id-type: auto
      table-prefix: ejyy_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mapper/*.xml