server:
  port: 8500

spring:
  application:
    name: payment-server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.14.75.238:3306/ejyy?useSSL=false&characterEncoding=UTF8
#    url: jdbc:mysql://127.0.0.1:3306/ejyy?useSSL=false&characterEncoding=UTF8
    username: root
    password: cyq0902
#    password: 123456
  redis:
    host: 1.14.75.238
    port: 6379
    database: 0
    timeout: 18000000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 1.14.75.238:8848
mybatis-plus:
  type-aliases-package: com.openlab.service.init.mapper
  global-config:
    db-config:
      id-type: auto
#      table-prefix: ejyy_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  httpclient:
    enabled: true
